import { FATLogo } from "./fat-logo"

export function Footer() {
  return (
    <footer className="w-full bg-background border-t border-[#333333] px-6 md:px-12 lg:px-24 py-12">
      <div className="mx-auto max-w-[1200px] flex flex-col md:flex-row items-center justify-between gap-6">
        <FATLogo />
        <p className="text-muted-foreground font-sans text-xs tracking-wide">
          Generated by Superagent.
        </p>
      </div>
    </footer>
  )
}
